name: GraalVM build
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with GraalVM
        run: mvn package
      - name: Rename binary based on OS
        run: |
           if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
             mv target/mcdec target/mcdec-macos
           elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
             mv target/mcdec target/mcdec-linux
           elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
             mv target/mcdec.exe target/mcdec-windows.exe
           fi
        shell: bash
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mcdec-${{ matrix.os }}
          path: target/mcdec-*

  release:
    name: Release binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List downloaded files (debugging)
        run: ls -R artifacts
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
